### PR TITLE
Add the fixed cross-compiled version of Zarith (which includes the right libdir)

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by TheLortex** [comment]
@dinosaure Maybe it took some time to launch, but now I see that the CI passed.

**Comment by dinosaure** [comment]
oh ok, thanks!

**Comment by dinosaure** [comment]
Hmmhmm, it seems that the solver did not take `zarith.1.12+dune1+mirage` (/cc @NathanReb). I mostly followed what is described on the `opam-overlays` which say:
> Once the PR is reviewed and merged, tag the head commit of dune-universe-vX.Y.Z with vX.Y.Z+dune2 (or +dune3, +dune4, etc.).

The `+mirage` misleads the solver probably?

**Comment by TheLortex** [comment]
Try `1.12+dune+mirage1` ? 

The problem is that version `dune+mirage` is greater than `dune1+mirage` according to the `OpamVersion.compare` function (https://ocaml.org/p/opam-core/2.1.2/doc/OpamVersion/index.html)

**Comment by dinosaure** [comment]
Hmmhmm, the problem still persist even if I renamed the package `zarith.1.12+dune+mirage1` 😕 .

**Comment by TheLortex** [comment]
I don't know why it's not selecting the new version. What happens if `zarith.1.12+dune+mirage` is removed ?

**Comment by dinosaure** [comment]
> I don't know why it's not selecting the new version. What happens if zarith.1.12+dune+mirage is removed ?

We can do that but it will lost a track of our update :confused:. I will do what you said when the last release fix an issue about cross-compiled OCaml runtime (and where *.h are different than the host OCaml compiler).

**Comment by dinosaure** [comment]
Rebased since mirage/mirage-skeleton#345 which fix our initial issue about the CI to take in account our PR.

**Pull request merged**
