### PR TITLE
add zarith 1.13 release

### LINKED ISSUE #5: zarith 1.13
Dear Madam or Sir,

it would be great if the latest zarith release, 1.13, could be integrated into this repository as well.

Thanks a lot!

### PR DESCRIPTION
**Pull request by hannesm**
fixes #5

### CODE REVIEW

**Comment by hannesm** [comment]
Hm, the CI is failing, but from the log I can't figure out what is actually going wrong? Any clues about that?

**Comment by hannesm** [comment]
debugging shows the error in zarith's configure:
```
+ ocamlc -custom -ccopt -L/src/_build/solo5/duniverse/Zarith/../../../install/solo5/lib/gmp/  tmp.ml -cclib -lgmp -o tmp.out
/usr/bin/ld: /src/_build/solo5/duniverse/Zarith/../../../install/solo5/lib/gmp//libgmp.so: file not recognized: file truncated
collect2: error: ld returned 1 exit status
File "tmp.ml", line 1:
Error: Error while building custom runtime system
```

I am now trying to revert the specific zarith commit, and go back to use $cc instead of $ocamlc. Another path may be to teach zarith to use our own (ocaml-solo5) ocamlc toolchain!?

let's take it how it is: our `libgmp.so` is an empty file, we're only doing statically linked builds anyways...

**Comment by hannesm** [comment]
ok, this is good for review and merge once CI passes. I avoided the issue above and re-released the package.

**Comment by hannesm** [comment]
CI is green \o/

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
